version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes
      MYSQL_USER: notes-api
      MYSQL_PASSWORD: password
    ports:
    - '3306:3306'
  db-test:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes-test
      MYSQL_USER: notes-api
      MYSQL_PASSWORD: password
    ports:
    - '3306:3306'
  app:
    build:
      context: ./
    environment:
      DATABASE_URL: mysql://notes-api:password@db:3306/notes
      TOKEN_SECRET: myTokenSecret
      TOKEN_TTL: 3600
      PORT: 3000
    ports:
    - '3000:3000'
    links:
     - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "3005:80"
    links:
      - db
